indexarchive = 'indexarchive.json'
resualt_html = 'resualt.html'
post_html = 'post.html'
index_html = 'index.html'
page1 = 'images\page1.jpg'
page1_tepl = 'images\page1_tepl.jpg'
BNAZANIN = 'BNAZANIN_0.ttf'
currency_url = 'https://www.tgju.org/currency'
coin_url = 'https://www.tgju.org/coin'
gold_url = 'https://www.tgju.org/gold-chart'
world_gold_url = 'https://www.goldapi.io/api/XAU/USD'
bource_url ='https://rahavard365.com/index/1/%DA%A9%D9%84-%D8%A8%D9%88%D8%B1%D8%B3'
bitcoin_url = 'https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd'